### GASTOS
GET http://localhost:3000/tarefa


### CREATE
POST http://localhost:3000/tarefa
content-type: application/json

{
  "nome": "Limpar a cozinha",
  "data": "05/01/2022",
  "recorrencia": 7.0,
  "timer": 20.00
}

### UPDATE
PUT http://localhost:3000/tarefa/3
content-type: application/json

{
  "nome": "Concluir projeto da faculdade",
  "data": "20/01/2022",
  "recorrencia": 1.0,
  "timer": 50.00
}


### GET GASTO
GET http://localhost:3000/tarefa/3

### DELETE GASTO
DELETE http://localhost:3000/tarefa/3
